### ISSUE TITLE
Online map request failure for Pl3xmap

### ISSUE THREAD

**Issue by shayypy** [thebuildcraft/RemotePlayerWaypointsForXaero#20] opened 2024-06-13 11:20 UTC
Hello, I'm receiving the following error for a Pl3xmap configuration. Below is my config file as requested in #19. The server is whitelisted but the map is accessible publicly.

![image](https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/43248357/5bd3513f-bbc1-4490-8890-a7bc96462545)

### Config

```json
{
	"enabled": true,
	"enablePlayerWaypoints": true,
	"enableMarkerWaypoints": true,
	// in ms
	"updateDelay": 2000,
	"serverEntries": [
		{
			"maptype": "Pl3xMap",
			"ip": "vanilla.xmcnet.work",
			"link": "https://map.xmcnet.work"
		}
	],
	// default Y coordinate for maps that don't provide Y coordinates
	"defaultY": 64,
	// in sec
	"timeUntilAfk": 300,
	"unknownAfkStateColor": 6316128,
	"AfkColor": 16733440,
	"playerWaypointColor": "Black",
	"markerWaypointColor": "Gray",
	"showAfkTimeInTabList": true,
	"debugMode": false,
	"ignoredServers": [],
	// in m
	"minDistance": 0,
	// in m
	"maxDistance": 100000,
	// in m
	"minDistanceMarker": 0,
	// in m
	"maxDistanceMarker": 100000
}
```

**Comment by thebuildcraft** [comment] 2024-06-13 15:08
That's weird... It works for me.
Could you please try and update all your mods and mod loader? If it still doesn't work, please send me the following information:
* Minecraft version
* Mod loader and version
* version of my mod
* list of other mods installed (with versions for the mods my mod depends on: Fabric / Quilt API, Xaeros maps, Cloth Config)

**Comment by shayypy** [comment] 2024-06-13 18:44
I made a new instance for testing:
- Minecraft 1.20.6
- Fabric 0.15.11
<img width="913" alt="image" src="https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/43248357/33bfe1d7-8ae7-426c-a20f-55d9a6b2a328">

Everything seems to be on the latest version.

**Comment by thebuildcraft** [comment] 2024-06-13 18:52
I don't know what is going on there... I have the exact same setup, just on my localhost server, and I'm connected to your Pl3xMap and it works fine.
Does this server have a lobby or is a server network?

**Comment by shayypy** [comment] 2024-06-13 18:55
No lobby, you just join and go straight into the world

**Comment by thebuildcraft** [comment] 2024-06-13 18:55
Is the mod outputting something to the logs?

**Comment by shayypy** [comment] 2024-06-13 19:00
Ah I should have checked that to start. Here are the logs from when it shows the error:
```
[14:46:48] [Timer-1/INFO]:
 new link: https://map.xmcnet.work/tiles/settings.json
[14:46:50] [Timer-1/INFO]:
 [System] [CHAT] [Remote Player Waypoints For Xaero's Map]: Failed to make online map request. Please check your config (probably your link...) or report a bug.
[14:46:50] [Timer-1/INFO]:
 [STDERR]: java.io.FileNotFoundException: https://map.xmcnet.work/tiles/minecraft:overworld/markers.json
[14:46:50] [Timer-1/INFO]:
 [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[14:46:50] [Timer-1/INFO]:
 [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[14:46:50] [Timer-1/INFO]:
 [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[14:46:50] [Timer-1/INFO]:
 [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.HTTP.makeTextHttpRequest(HTTP.java:72)
[14:46:50] [Timer-1/INFO]:
 [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.HTTP.makeJSONHTTPRequest(HTTP.java:61)
[14:46:50] [Timer-1/INFO]:
 [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.connections.Pl3xMapConnection.getMarkerLayers(Pl3xMapConnection.java:115)
[14:46:50] [Timer-1/INFO]:
 [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.connections.Pl3xMapConnection.getWaypointPositions(Pl3xMapConnection.java:97)
[14:46:50] [Timer-1/INFO]:
 [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.UpdateTask.run(UpdateTask.java:148)
[14:46:50] [Timer-1/INFO]:
 [STDERR]: 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
[14:46:50] [Timer-1/INFO]:
 [STDERR]: 	at java.base/java.util.TimerThread.run(Unknown Source)
[14:46:52] [Timer-1/INFO]:
 new link: https://map.xmcnet.work/tiles/settings.json
[14:46:52] [Timer-1/INFO]:
 [STDERR]: java.io.FileNotFoundException: https://map.xmcnet.work/tiles/minecraft:overworld/markers.json
[14:46:52] [Timer-1/INFO]:
 [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[14:46:52] [Timer-1/INFO]:
 [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[14:46:52] [Timer-1/INFO]:
 [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[14:46:52] [Timer-1/INFO]:
 [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.HTTP.makeTextHttpRequest(HTTP.java:72)
[14:46:52] [Timer-1/INFO]:
 [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.HTTP.makeJSONHTTPRequest(HTTP.java:61)
[14:46:52] [Timer-1/INFO]:
 [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.connections.Pl3xMapConnection.getMarkerLayers(Pl3xMapConnection.java:115)
[14:46:52] [Timer-1/INFO]:
 [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.connections.Pl3xMapConnection.getWaypointPositions(Pl3xMapConnection.java:97)
[14:46:52] [Timer-1/INFO]:
 [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.UpdateTask.run(UpdateTask.java:148)
[14:46:52] [Timer-1/INFO]:
 [STDERR]: 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
[14:46:52] [Timer-1/INFO]:
 [STDERR]: 	at java.base/java.util.TimerThread.run(Unknown Source)
```

**Comment by shayypy** [comment] 2024-06-13 19:03
I looked on the server filesystem and the path for the directory `minecraft-overworld` resolves but not `minecraft:overworld`. So `https://map.xmcnet.work/tiles/minecraft-overworld/markers.json` instead of `https://map.xmcnet.work/tiles/minecraft:overworld/markers.json`

**Comment by thebuildcraft** [comment] 2024-06-13 19:14
I have found the issue:
![grafik](https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/104298589/10df0dd8-b77d-4dff-81a3-94d7d450b92a)
In the player data, it is "minecraft:overworld" but in the marker data it is "minecraft-overworld". On my local test server it works. And the test with your server also worked, because it never tried to get the markers, because it never found me on your map, because I was on my test server.
Could you try to disable the marker waypoints in your config, please?

**Comment by shayypy** [comment] 2024-06-13 19:31
I removed the markers but the same error still occurs in the logs and in chat. Correct me if I'm wrong but is this not because the player list is showing `minecraft:overworld` when the real path is what's shown in `worldSettings`? I would think that I need to correct/compensate for what plexmap is serving in `players`?

**Comment by thebuildcraft** [comment] 2024-06-13 19:39
I'm sorry, but don't fully get what you are saying...
The problem is how my code generates the http get request link for the markers: it uses the world name of the player using the mod to figure out from which world to take the markers from. I need to do this, because some servers have more than the usual 3 dimensions.
And also: did you disable the marker display in my mod, or on your server? Because I meant, you should disable it in my client mod so that it hopefully won't throw that error.
Anyway... it's getting late for me. I will have another look at it tomorrow.

**Comment by shayypy** [comment] 2024-06-13 19:47
Oh sorry, I thought you meant on the server, so I removed the markers. Yes, disabling the marker waypoints setting in your mod allows it to load normally.

**Comment by thebuildcraft** [comment] 2024-06-18 16:52
I was just about to try to fix your issue... Then I noticed that your server switched to Bluemap. I'm also unable to reproduce this issue on other Pl3xMaps. Do you still have some problems with my mod? Otherwise, I can close this issue.

**Comment by shayypy** [comment] 2024-06-19 21:48
Sorry about that, I was trying to push for Pl3xmap because of this issue but we switched anyway after 1.21. I've started another instance of our plexmap-enabled 1.20.6 server if you would like to be whitelisted on it for testing. The map link for this instance is https://map.nj.xmcnet.work.

**Comment by thebuildcraft** [comment] 2024-06-20 04:04
Thank you so much!
Yes, I would like to be whitelisted because this issue is very hard to debug otherwise.
I will then try to fix it (and port to 1.21) as soon as I can.

**Comment by shayypy** [comment] 2024-06-20 11:14
Can do, what is your minecraft username?

**Comment by thebuildcraft** [comment] 2024-06-20 12:26
Oh, yes sorry...
the_build_craft

**Comment by shayypy** [comment] 2024-06-20 12:56
👍 you're whitelisted on `vanilla.nj.xmcnet.work`

**Comment by thebuildcraft** [comment] 2024-06-20 12:57
Thank you, I will look at it later.

**Closed** 2024-06-21 18:57 UTC

**Comment by thebuildcraft** [comment] 2024-06-21 19:01
Hi. I fixed the bug. The fix probably looks too simple. But from my understanding it is all that is needed.
For the case, that some other problems with marker get-requests occur, I have some other fixes not committed yet, where I put the marker request in a separate try catch block. I will release them together with some other refactors to the whole UpdateTaks.

And thanks again for providing your server for testing!

**Comment by shayypy** [comment] 2024-06-21 21:47
Thanks! 🎉
